[package]
edition = "2021"
name = "squarecl-macros"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
derive_more = { version = "1.0.0", features = ["display"] }
prettyplease = "0.2.20"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.75", features = ["full", "visit"] }
